from typing import Protocol

from src.domain.entities.user import User


class UserRepository(Protocol):
    def find_by_email(self, email: str) -> User | None: ...
    def find_by_id(self, user_id: str) -> User | None: ...
    def save(self, user: User) -> None: ...
    def exists_by_email(self, email: str) -> bool: ...
