from enum import Enum


class DepartmentType(str, Enum):
    SECRETARIA = "SECRETARIA"
    DEPARTAMENTO_ADMINISTRATIVO = "DEPARTAMENTO_ADMINISTRATIVO"
    SUBSECRETARIA = "SUBSECRETARIA"
    ENTE_DESCENTRALIZADO = "ENTE_DESCENTRALIZADO"
